name: Generar APK

on:
  push:
    branches:
      - principal
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Preparar proyecto
        run: |
          mkdir -p proyecto
          unzip -o FinanzasPersonalesV1_GitHub_final.zip -d proyecto

          ROOT=$(find proyecto -name settings.gradle.kts -o -name settings.gradle | head -n 1)
          ROOT=$(dirname "$ROOT")

          echo "Proyecto encontrado en: $ROOT"

          cp -r "$ROOT"/. .

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.10'

      - name: Compilar APK
        run: |
          gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: FinanzasPersonales-APK
          path: "**/build/outputs/apk/debug/*.apk"
